### ISSUE TITLE
Implement ability to use existant tox IDs

### ISSUE THREAD

**Issue by DoctorJellyface** [KoKuToru/gTox#102]
I can't really use gTox without this.

**Comment by KoKuToru** [comment]
You meaning loading toxcore profiles of other clients ?

**Comment by DoctorJellyface** [comment]
Yeah.

**Comment by DoctorJellyface** [comment]
qTox and uTox can both do this I think.

**Comment by KoKuToru** [comment]
Well .. uTox has a very old "toxcore profile" (or mine had).
We use the newest toxcore, it gives a ERROR-Code when loading these old files.
It's possible to load them, but gTox doesn't allow it at the moment.
(you should see them in the profile selection.. but it will be shown as "Corrupted profile")
Because if I "upgrade" these profiles, you probably wont be able to load it in uTox or qTox.

And because we use the newest toxcore.. you can't chat with clients using the old toxcore..
So it's hardly useable this way..

That said.. I am working on this "upgrade" and will try if uTox can still load the "upgrade"-file..

**Comment by DoctorJellyface** [comment]
Oh, I'm running an old version. gTox in the AUR is still from December ;)

**Comment by DoctorJellyface** [comment]
Cool, everything works fine now! Feel free to close this.

**Comment by KoKuToru** [comment]
Nope AUR uses git. If you reinstall it it should use the newest.
Anyways, I used the newest uTox via AUR.

It does work. It's a problem with gTox .. 
The new Profile selector. Can't load "tox_save.tox" files.. because it checks for "tox_save" (old path for profiles).
And new uTox saves it into "tox_save.tox" .. need to modify gTox a little that it can see the "tox_save" and the "tox_save.tox"

or better if "tox_save.tox" exists .. ignore "tox_save" .. meeh

**Comment by KoKuToru** [comment]
Okay .. if it works.. nice :+1: 

But it's still a problem.. gTox wont load "tox_save.tox" when "tox_save" exists

**Comment by DoctorJellyface** [comment]
I do see it in the profile selector.

**Comment by DoctorJellyface** [comment]
Cool, thanks.
