### ISSUE TITLE
Couldn't locate locale

### ISSUE THREAD

**Issue by Ogromny** [KoKuToru/gTox#74]
Hi,
I'm on Arch and when i do
gTox
I got this
Couldn't locate locale

**Comment by KoKuToru** [comment]
Could you show me your output for `locale` and `locale -a` ?
We probably will need to move away from `gettext`, it just doesn't work as I would like..

Thinks you can try:
 `LC_ALL=C ./gTox` and/or `LC_ALL=en ./gTox`

**Comment by Ogromny** [comment]
locale:
LANG=fr_FR.utf8
LC_CTYPE="fr_FR.utf8"
LC_NUMERIC="fr_FR.utf8"
LC_TIME="fr_FR.utf8"
LC_COLLATE="fr_FR.utf8"
LC_MONETARY="fr_FR.utf8"
LC_MESSAGES="fr_FR.utf8"
LC_PAPER="fr_FR.utf8"
LC_NAME="fr_FR.utf8"
LC_ADDRESS="fr_FR.utf8"
LC_TELEPHONE="fr_FR.utf8"
LC_MEASUREMENT="fr_FR.utf8"
LC_IDENTIFICATION="fr_FR.utf8"
LC_ALL=

locale -a:
C
fr_FR.utf8
POSIX

**Comment by KoKuToru** [comment]
Yeah .,. this means it will search for `fr` translation and wont fallback to `en`
and because there is no `en` in `locale -e`.. 
You probably can't even change it with `LC_ALL`

Which sucks. I wanted to use this translation system of `gettext` but it just makes it harder.
I will need to search for a way to force it to `en`, when the requested translation does not exists.

**Comment by Ogromny** [comment]
:( oh shit ok

**Comment by KoKuToru** [comment]
Just found out
`LANGUAGE=en ./gTox?`
should work !

I thought languages are changed with `LC_ALL`..
Need to investigate this.

**Comment by Ogromny** [comment]
ok but how can i add this to my locale, i've searched but not found :(

**Comment by KoKuToru** [comment]
just do in a terminal (bash):
`LANGUAGE=en ./gTox`
in the folder where you compiled gTox

**Comment by Ogromny** [comment]
Ok thanks its work now :D +1

**Comment by Ogromny** [comment]
but how can import a utox account ?

**Comment by KoKuToru** [comment]
You can't right now..
